#!/usr/bin/env bash

register_desktop_app=0

while :
do
    case "$1" in
    	--register-app)
          register_desktop_app=1
          show_output=1
          shift
          ;;
      --unregister-app)
          register_desktop_app=-1
          show_output=1
          shift
          ;;
      *) # No more options
          break
          ;;
    esac
done

# remove installed app
if [ "$register_desktop_app" -eq -1 ]; then
  if [ -e "$HOME/.local/share/applications/encryptsync.desktop" ]; then
    rm -f "$HOME/.local/share/applications/encryptsync.desktop"
    update-desktop-database "$HOME/.local/share/applications/"
    printf "Encrypt-Sync has been removed as a user desktop app (from ~/.local/share/applications/)\n"
  else
    printf "Encrypt-Sync does not appear to be a desktop app (not present in ~/.local/share/applications/)\n"
  fi
  if [ -e "$HOME/Desktop/encryptsync.desktop" ]; then
    rm -f "$HOME/Desktop/encryptsync.desktop"
  fi

  exit 0
fi

# Fix up .desktop Icon and Exec Paths, and update the .desktop file from the canonical version.
cp ./templates/encryptsync.desktop ./encryptsync.desktop
sed -i -e "s,^Icon=.*,Icon=$PWD/encryptsync.png,g" ./encryptsync.desktop
sed -i -e "s,^Path=.*,Path=$PWD,g" ./encryptsync.desktop
sed -i -e "s,^Exec=.*,Exec=node $PWD/main.js,g" ./encryptsync.desktop
chmod u+x ./encryptsync.desktop
chmod u+x ./start-encryptsync

# register the app
if [ "$register_desktop_app" -eq 1 ]; then
	mkdir -p "$HOME/.local/share/applications/"
  cp ./encryptsync.desktop "$HOME/.local/share/applications/"
	cp ./encryptsync.desktop "$HOME/Desktop"
  chmod u+x $HOME/Desktop/encryptsync.desktop
	update-desktop-database "$HOME/.local/share/applications/"
	printf "Encrypt-Sync has been registered as a desktop app for this user in ~/.local/share/applications/\n"
	exit 0
fi